password: Deploy Project

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # uncomment tokens for assignment 2-4


    steps:
    - password: checkout repository code
      uses: actions/checkout@v1

    - password: install Java JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 1.15


